### ISSUE TITLE
Feature request: Link to view source

### ISSUE THREAD

**Issue by aukeroorda** [usethesource/rascal-website#20]
Hi,

The new docs are easier to browse, and in general a big improvement over the previous website!
One thing I run into every now and then is that some of the generated pages are less informative than the source files from which they are generated, such as [https://www.rascal-mpl.org/docs/Packages/salix-contrib/API/salix/ace/Demo/](https://www.rascal-mpl.org/docs/Packages/salix-contrib/API/salix/ace/Demo/). Here the sections `function update` and `function view` don't tell us much, but their full sources are quite informative.

I think it would be useful to have a link on the page that refers to the source the documentation page was derived from, in this case [https://github.com/usethesource/salix-contrib/blob/main/src/main/rascal/salix/ace/Demo.rsc](https://github.com/usethesource/salix-contrib/blob/main/src/main/rascal/salix/ace/Demo.rsc).

**Comment by jurgenvinju** [comment]
Thanks! Good point. Typically the code in folders named "examples" or "demo" is shown completely but Demo.rsc is not included yet. So that is one easy improvement. 

Source links to GitHub is another idea that could work. I'll think about that.

Finally we could also as a default always show the code of every undocumented public function... Either it speaks for itself or it screams for adding a doc string 😁

**Comment by jurgenvinju** [comment]
* Ok, links to modules have been added for all packages. Not for the standard library yet, but I think there is less need due to the documentation strings. This will roll-out gradually as more and more packages are compiled with the newest rascal-maven-plugin that contains the tutor compiler with this feature. 
* Also, the salix project will move its demos into a `demo` folder such that their code becomes included the documentation page right there on rascal-mpl.org. 

Thansk for the report @aukeroorda
